---
site_name: Cookiecutter Python Project
site_author: Lyz
site_url: https://lyz-code.github.io/cookiecutter-python-project
nav:
  - Overview: index.md
  - Contributing: contributing.md

plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - def_list
  - admonition
  - markdown_include.include:
      base_path: docs
  - meta
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  custom_dir: docs/theme
  # logo: 'images/logo.bmp'
  features:
    - navigation.instant
  palette:
    primary: blue grey
    accent: light blue

extra_css:
  - stylesheets/extra.css
  - stylesheets/links.css

repo_name: lyz-code/cookiecutter-python-project
repo_url: https://github.com/lyz-code/cookiecutter-python-project
