---
name: Install
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: 21 08 * * *

jobs:
  Install:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
        uses: actions/setup-python@v1
        with:
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
      - name: Install the program
        run: pip install {{ cookiecutter.project_slug }}
      - name: Test the program works
{%- if cookiecutter.configure_command_line == "True" %}
        run: {{ cookiecutter.project_slug }} --version
{% else %}
        run: |
          python -c "import {{ cookiecutter.project_underscore_slug }}.version;
          print({{ cookiecutter.project_underscore_slug }}.version.version_info())"
{% endif -%}
