---
name: Tests

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10']
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
        uses: actions/setup-python@v1
        with:
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
      - name: Install program
        run: |
          # All these steps are required so that mypy behaves equally than the
          # local environment, once mypy supports __pypackages__ try to use the
          # github action
          pip install virtualenv pdm
          virtualenv .venv
          source .venv/bin/activate
          pdm config use_venv True
          make install
      - name: Test linters
        run: make lint
      - name: Test type checkers
        run: make mypy
      - name: Test security
        run: make security
      - name: Test with pytest
        run: make test
      - name: Upload Coverage
        run: |
          pip3 install 'coveralls[toml]'
          coveralls --service=github
        env:
          GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
          COVERALLS_FLAG_NAME: {% raw %}${{ matrix.test-name }}{% endraw %}
          COVERALLS_PARALLEL: true
      - name: Test documentation
        run: make build-docs
      - name: Build the package
        run: make build-package
  Coveralls:
    name: Finish Coveralls
    needs: Tests
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        run: |
          pip3 install 'coveralls[toml]'
          coveralls --service=github --finish
        env:
          GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
